openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: A sample API for demonstration
servers:
  - url: http://localhost:3000
paths:
  /login:
    post:
      summary: Authenticate a user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid username or password

  /logout:
    post:
      summary: Logout a user
      tags: [Auth]
      responses:
        '200':
          description: Logout successful
        '500':
          description: Server error during logout

# הוסף כאן נתיבים נוספים...